### ISSUE TITLE
[BUG] Debug output from serverless (sls) is not provided

### ISSUE THREAD

**Issue by ajhool** [flowaccount/nx-plugins#15]
**Describe the bug**
When using the `nx run-many --targets=deploy --all` command, deployments can fail silently. The failures are usually correct, eg. bad underlying `serverless.yml` file, but there is no way to debug the failure without the log output from serverless.

**To Reproduce**

```
yarn create nx-workspace todo-list-app
  ? What to create in the new workspace react-express     [a workspace with a full stack application (React + Express)]
  ? Application name                    todo-list-app
  ? Default stylesheet format           CSS 

yarn add -D @flowaccount/nx-serverless
nx generate @flowaccount/nx-serverless:application --name=sls-api --provider=aws --no-interactive
```

Add an error to the serverless.yml file, like this badly indented "vpc" parameter:

```
functions:
  # https://serverless.com/framework/docs/providers/aws/guide/variables/#referencing-environment-variables
  hello-world:
    handler: src/handler.helloWorld
    events:
      - http:
          path: hello-world
          method: get
  vpc:
     subnetIds:
        - 'Hello, nice to meet you, I am an error'
```

**Expected behavior**

**Screenshots**

**Check which provider is affected:**
[x] AWS
[probably] Azure
[probably] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[x] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
Linux

Set the SLS_DEBUG flag:

`export SLS_DEBUG=true`

**The silent failure of `nx deploy --target=deploy`**

```
Serverless: Load command param:get
Serverless: Load command param:list
Hash: dcbfaafc7f35681865e0
Built at: 03/15/2020 3:43:52 PM
Entrypoint src/handler = src/handler.js
chunk    {0} src/handler.js (src/handler) 412 bytes [entry] [rendered]
[0] external "tslib" 42 bytes {0} [built]
    [1] 1617ms -> factory:3ms building:1ms = 1621ms
[1] ./apps/sls-api-v2/src/handler.ts 370 bytes {0} [built]
    factory:1278ms building:339ms = 1617ms
Serverless: getting external modules
Serverless: create a package.json with first level dependencies
Serverless: generate lock entry for yarn for dependency graph to work.
Serverless: get the packagelist with dependency graph and depth=2 level
Serverless: re-writing package.json with dependency-graphs
Serverless: WARNING: Could not determine version of module tslib
Serverless: run packager to  install node_modules
Serverless: yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.55s.

Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...


———————————————————————————————————————————————


>  NX   ERROR  Running target "deploy" failed

  Failed projects:
  
  - sls-api-v2
  
  You can isolate the above projects by passing: --only-failed
```

**The native output with helpful output of serverless: `serverless deploy`. In this case, "vpc" is being interpreted as a separate lambda function rather than a parameter of hello-world**

```
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Missing "handler" property in function "vpc". Please make sure you point to the correct lambda handler. For example: handler.hello. Please check the docs for more info
```

**Comment by ajhool** [comment]
@wickstargazer 

This is becoming a pressing issue for us because we can't deploy due to an error but can't find error output.

(i) Where in the code should we be looking for the issue?

(ii) We are finding that running `serverless deploy` in the `apps/my-api` folder is succeeding but running `nx run-many --target=deploy --all` is failing. We have two nx serverless apps and only one is failing with nx deploy. Does the `serverless deploy` command need more parameters to be identical to nx?

**Comment by wickstargazer** [comment]
Hi, sorry for the late reply, been some hectic days without coding! 

Can I have a sample repo? or if there is a `serverless.yml` i can use to reproduce the problem?

Also which version of serverless are you using? I found a bug since it was written for 1.5 and they changed the way the --options are passed in, fixing that as we speak.

Also looking into the debug flag :)

Please let me know if you can provide more info!

**Comment by wickstargazer** [comment]
Hey @ajhool i found the issue
the `is-builtin-module` is missing in the `package.json` dependency of the lib.

It is fixed in `0.4.61`

I am really sorry it got delayed and i pretty much screwed up 😞 

Anyways please let me know if can help with something else 🍡

**Comment by ajhool** [comment]
> Hey @ajhool i found the issue
> the `is-builtin-module` is missing in the `package.json` dependency of the lib.
> 
> It is fixed in `0.4.61`

Nice find!

> I am really sorry it got delayed and i pretty much screwed up disappointed

This was a remarkably quick response and patch, thank you and there is of course no need for apologies :)

> Anyways please let me know if can help with something else dango

It might be an issue with integrating the latest patch into our existing project, but I am still seeing the same or a similar issue with the most recent update. I will set up a demo repo right now to (a) see if a new project resolves the issue and (b) use as a repro environment

Lack of a "plugin migration" command for `nrwl/nx`, itself, seems like a pretty big issue with the framework that will make developing and using these plugins quite difficult, IMO. I'm curious if/how they plan to work through that.

**Comment by wickstargazer** [comment]
any updates @ajhool ?

**Comment by wickstargazer** [comment]
Hi @ajhool i will consider this as closed? ..since i havent heard from you for a while, we can always re-open it and i can help you get the setup right :D
